name: 'App Build'
description: 'Builds app package for openHAB Windows app'

inputs:
  build_configuration:
    description: 'Defines build configuration (debug or release)'
    required: false
    default: 'release'

  output_directory: 
    description: 'Defines the output directory for the app package'
    required: false
    default: '${{github.workspace}}\build'

  GITHUB_TOKEN: 
    description: 'Token for Authentication with GitHub'
    required: true

  SONAR_TOKEN: 
    description: 'Token for Authentication with Sonar Cloud'
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Version Number in app files
      id: update-packageverion
      shell: pwsh
      run: | 
            Set-Location ${{github.action_path}}/
            $major= [System.DateTime]::Now.Year
            $minor = [System.DateTime]::Now.Month
            $build = [System.DateTime]::Now.Day

            ./Set-Version.ps1 -SourceDirectory '${{github.workspace}}\src\' -Major $major -Minor $minor -Build $build -Revision 0 -SetVersion

    - name: Restore nuget packages
      shell: pwsh
      run: |
            Write-Host "==== Restore Nuget packages ====" -ForegroundColor Green
            nuget restore ${{github.workspace}}\src\OpenHAB.Windows.sln
    
    - name: Build OpenHab Windows App
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
        SONAR_TOKEN: ${{inputs.SONAR_TOKEN}}
      run: |
          Write-Host "==== Build app package ====" -ForegroundColor Green
          msbuild.exe ${{github.workspace}}\src\OpenHAB.Windows.sln /p:Platform="x86" /p:AppxBundlePlatforms="x86|x64|ARM" /p:AppxPackageDir="${{inputs.output_directory}}" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:configuration="${{inputs.build_configuration}}" /t:rebuild