name: App Release

env:
  BuildDirectory: '${{github.workspace}}\build'

on:
  workflow_call:
    inputs:
      force_release:
        description: 'Specifies if a release should be created even if the branch is not main.'
        type: boolean
        default: false
        required: false
      beta_release:
        description: 'Specifies if a beta release should be created.'
        type: boolean
        default: false
        required: false
      build_number:
        type: string
        description: 'The build number to use'
        required: true

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  release:
      name: 'App release creation for ${{inputs.build_number}}'
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/releases/beta' || inputs.force_release == true
      steps:
        - name: Download a App Package from Build Artifacts
          uses: actions/download-artifact@v4
          with:
            name: app
            path: '${{env.BuildDirectory}}'

        - name: Display structure of downloaded files
          run: ls -la
          working-directory: '${{env.BuildDirectory}}'

        - name: Create a Release
          id: create_release
          uses: marvinpinto/action-automatic-releases@latest
          working-directory: '${{env.BuildDirectory}}'
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: ${{inputs.beta_release}}
            automatic_release_tag: ${{inputs.build_number}}
            title: ${{inputs.build_number}}
            files: |
              **/*.msixbundle
